from systemd import journal
from collections.abc import Iterator
from models.raw_log import RawLog
from .base import BaseCollector


class JournalCollector(BaseCollector):

    """
    Collects live system logs from the Linux systemd journal.

    This collector uses systemd.journal.Reader to monitor journal entries
    in real-time and converts raw journal records into normalized RawLog
    objects consumed by the SIEM processing pipeline.

    Currently, it monitors SSH service events and collects authentication-
    related logs generated by OpenSSH.

    The collector operates in follow mode:
        1. Positions the journal cursor at the current end of the log.
        2. Waits for new journal entries using systemd journal notifications.
        3. Reads appended entries as they appear.
        4. Converts valid entries into RawLog models.

    Notes:
        - journal.Reader.get_next() may return an empty dictionary ({})
          when no more entries are available, so empty entries must be
          ignored before processing.
        - seek_tail() requires moving the cursor backward once using
          get_previous() to correctly follow new appended entries.

    Future improvements:
        - Support multiple journal sources instead of only SSH.
        - Add configurable filters for different system services.
        - Support persistent cursor storage for agent restarts.
    """

    def __init__(self):

        self.reader = journal.Reader()

        self.reader.this_boot()

        self.reader.add_match(
            _SYSTEMD_UNIT="ssh.service"
        )

        self.reader.seek_tail()

        # Move cursor to the last existing entry.
        # Required so get_next() can correctly receive future appended logs.
        self.reader.get_previous()

    def collect(self):

        while True:

            if self.reader.wait() != journal.APPEND:
                continue

            while True:

                entry = self.reader.get_next()
                
                # systemd journal returns an empty dict when no more entries exist.
                # Stop reading until the next journal append notification.
                if not entry:
                    break

                required = (
                    "__REALTIME_TIMESTAMP",
                    "_HOSTNAME",
                    "SYSLOG_IDENTIFIER",
                    "MESSAGE",
                )

                if not all(key in entry for key in required):
                    continue

                yield RawLog(
                    timestamp=entry["__REALTIME_TIMESTAMP"],
                    hostname=entry["_HOSTNAME"],
                    identifier=entry["SYSLOG_IDENTIFIER"],
                    message=entry["MESSAGE"],
                )